import { Routes } from '@angular/router';
import { HomeComponent } from './pages/home/home';
import { AboutComponent } from './pages/about/about';
import { LoginComponent } from './pages/login/login';
import { RegisterComponent } from './pages/register/register';
import { ProfileComponent } from './pages/profile/profile';
import { DistrictComponent } from './pages/district/district';
import { InnovativeComponent } from './pages/innovative/innovative';
import { ProgramsComponent } from './pages/programs/programs';
import { CentersComponent } from './pages/centers/centers';
import { TransformationComponent } from './pages/transformation/transformation';
import { DashboardHomeComponent } from './pages/dashboard/dashboard-home';
import { CoursesComponent } from './pages/courses/courses';
import { DirectorDashboardComponent } from './pages/director-dashboard/director-dashboard';
import { PartnerDashboardComponent } from './pages/partner-dashboard/partner-dashboard';
import { StudentNearbyComponent } from './pages/student-nearby/student-nearby';
import { TeacherDashboardComponent } from './pages/teacher-dashboard/teacher-dashboard';
import { ContactPageComponent } from './pages/contact/contact';
import { PublicWorkshopsPageComponent } from './pages/workshops/workshops';
import { IssuesPageComponent } from './pages/issues/issues';
import { DonatePageComponent } from './pages/donate/donate';
import { InvestPageComponent } from './pages/invest/invest';
import { StudentDashboardComponent } from './pages/student-dashboard/student-dashboard';
import { HealthConnectComponent } from './pages/health-connect/health-connect';
import { MyScheduleComponent } from './pages/my-schedule/my-schedule';
import { MyProfileComponent } from './pages/my-profile/my-profile';
import { ProgramDetailComponent } from './pages/program-detail/program-detail';
import { ResearchPageComponent } from './pages/research/research';
import { ResearchNewComponent } from './pages/research/research-new/research-new';
import { MyWorkshopsComponent } from './pages/workshops/my-workshops/my-workshops';
import { EnrolledWorkshopsComponent } from './pages/workshops/enrolled-workshops/enrolled-workshops';

export const routes: Routes = [
    { path: '', component: HomeComponent },
    { path: 'dashboard', component: DashboardHomeComponent },
    { path: 'dashboard/courses', component: CoursesComponent },
    { path: 'dashboard/director', component: DirectorDashboardComponent },
    { path: 'dashboard/partner', component: PartnerDashboardComponent },
    { path: 'dashboard/student', component: StudentDashboardComponent },
    { path: 'dashboard/student/nearby', component: StudentNearbyComponent },
    { path: 'dashboard/teacher', component: TeacherDashboardComponent },
    { path: 'dashboard/teacher/workshops', redirectTo: 'workshops', pathMatch: 'full' },
    { path: 'dashboard/my-workshops', component: MyWorkshopsComponent },
    { path: 'dashboard/enrolled-workshops', component: EnrolledWorkshopsComponent },
    { path: 'about', component: AboutComponent },
    { path: 'login', component: LoginComponent },
    { path: 'register', component: RegisterComponent },
    { path: 'profile', component: ProfileComponent },
    { path: 'contact', component: ContactPageComponent },
    { path: 'district', component: DistrictComponent },
    { path: 'issues', component: IssuesPageComponent },
    { path: 'donate', component: DonatePageComponent },
    { path: 'invest', component: InvestPageComponent },
    { path: 'innovative', component: InnovativeComponent },
    { path: 'courses', component: InnovativeComponent },
    { path: 'programs', component: ProgramsComponent },
    { path: 'programs/:programId', component: ProgramDetailComponent },
    { path: 'programs/:programId/:sectionId', component: ProgramDetailComponent },
    { path: 'programs/:programId/:sectionId/:subSectionId', component: ProgramDetailComponent },
    { path: 'workshops', component: PublicWorkshopsPageComponent },
    { path: 'transformation', component: TransformationComponent },
    { path: 'centers', component: CentersComponent },
    { path: 'health-connect', component: HealthConnectComponent },
    { path: 'my-schedule', component: MyScheduleComponent },
    { path: 'my-profile', component: MyProfileComponent },
    { path: 'research/new', component: ResearchNewComponent },
    { path: 'research', component: ResearchPageComponent },
    { path: '**', redirectTo: '' }
];
